# Generated by Django 4.2.6 on 2023-10-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("age", models.SmallIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("streak", models.SmallIntegerField(blank=True, null=True)),
                ("total_points", models.SmallIntegerField(blank=True, null=True)),
                ("total_co2e_reduced", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EcoTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=50)),
                ("distance", models.FloatField()),
                ("co2_reduced", models.FloatField(blank=True, null=True)),
                (
                    "ecoTransport_points",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("activity_date", models.DateField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EcoQuestApp.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EcoEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.SmallIntegerField(blank=True, null=True)),
                ("activity_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("text", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EcoQuestApp.profile",
                    ),
                ),
            ],
        ),
    ]
