# Generated by Django 4.2.6 on 2023-10-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_breakfast', models.BooleanField(default=False)),
                ('eco_lunch', models.BooleanField(default=False)),
                ('eco_dinner', models.BooleanField(default=False)),
                ('co2_reduced', models.FloatField(blank=True, null=True)),
                ('ecomeals_points', models.SmallIntegerField(blank=True, null=True)),
                ('entry_date', models.DateField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuestApp.profile')),
            ],
        ),
    ]
