# Generated by Django 4.2.6 on 2023-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecotransport',
            name='activity_date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
