# Generated by Django 4.1 on 2023-10-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0002_ecomeals'),
        ('EcoQuestApp', '0002_rename_ecoeducation_points_ecoeducation_points_and_more'),
    ]

    operations = [
    ]
