# Generated by Django 4.2.6 on 2023-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_co2e_reduced',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
