# Generated by Django 4.2.6 on 2023-10-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0002_ecotransport_activity_date_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecotransport',
            name='distance',
            field=models.FloatField(),
        ),
    ]
