# Generated by Django 4.2.6 on 2023-10-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuestApp', '0003_alter_profile_total_co2e_reduced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecotransport',
            old_name='co2_reduced',
            new_name='transport_co2_reduced',
        ),
    ]
