# Generated by Django 4.2.6 on 2023-10-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EcoQuestApp", "0005_ecoeducation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ecoeducation",
            old_name="ecoEducation_points",
            new_name="points",
        ),
        migrations.RemoveField(
            model_name="ecoeducation",
            name="activity",
        ),
        migrations.AddField(
            model_name="ecoeducation",
            name="text",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
