# Generated by Django 4.2.6 on 2023-10-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EcoQuestApp", "0006_rename_ecoeducation_points_ecoeducation_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecoeducation",
            name="activity_date",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
